name: hypertypes
version: 0.3.0
github: "lamdu/hypertypes"
license: BSD3
author: "Yair Chuchem"
maintainer: "yairchu@gmail.com"
copyright: 2018 Yair Chuchem

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Generic programming for mutually-recursive data types
category: Data, Generics

description: Please see the README on GitHub at <https://github.com/lamdu/hypertypes#readme>

dependencies:
- base >= 4.9 && <5

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies
- NoImplicitPrelude

ghc-options:
- -fexpose-all-unfoldings
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Wunused-packages
ghc-prof-options:
- -fexpose-all-unfoldings

library:
  source-dirs: src
  other-modules:
  - Hyper.Internal.Prelude
  - Hyper.TH.Internal.Utils
  dependencies:
  - base-compat
  - binary
  - constraints
  - containers
  - deepseq
  - generic-constraints
  - generic-data
  - lens
  - pretty
  - template-haskell
  - transformers
  - th-abstraction >= 0.6
  ghc-options:
  - -Wnoncanonical-monad-instances
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

tests:
  hypertypes-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hypertypes
    - lens
    - tasty
    - tasty-hunit
