name: hypertypes
version: 0.2.3
github: "lamdu/hypertypes"
license: BSD3
author: "Yair Chuchem"
maintainer: "yairchu@gmail.com"
copyright: 2018 Yair Chuchem"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Typed ASTs
category: Algorithms, Compilers/Interpreters, Language, Logic, Unification

description: Please see the README on GitHub at <https://github.com/lamdu/hypertypes#readme>

dependencies:
- base >= 4.9 && <5
- constraints
- containers
- generic-constraints
- generic-data
- lattices
- lens
- monad-st
- mtl
- pretty

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies
- NoImplicitPrelude

ghc-options:
- -fexpose-all-unfoldings
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Wunused-packages
ghc-prof-options:
- -fexpose-all-unfoldings

library:
  source-dirs: src
  other-modules:
  - Hyper.Internal.Prelude
  - Hyper.TH.Internal.Utils
  dependencies:
  - array
  - base-compat
  - binary
  - deepseq
  - pretty
  - show-combinators
  - template-haskell
  - transformers
  - th-abstraction >= 0.6
  ghc-options:
  - -Wnoncanonical-monad-instances
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

tests:
  hypertypes-test:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: false
      other-modules:
      - Benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hypertypes
    - tasty
    - tasty-hunit
    - text

benchmarks:
  hypertypes-bench:
    main: Benchmark.hs
    source-dirs: test
    other-modules:
    - LangB
    - TypeLang
    ghc-options:
    - -O2
    - -Wnoncanonical-monad-instances
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    dependencies:
    - criterion
    - hypertypes
