name:                syntax-tree
version:             0.1.0.0
github:              "githubuser/syntax-tree"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/syntax-tree#readme>

dependencies:
- base
- base-compat
- binary
- containers
- lens
- mtl
- pretty
- QuickCheck
- transformers

library:
  source-dirs: src

executables:
  syntax-tree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syntax-tree

tests:
  syntax-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - lens
    - syntax-tree
